name: flutterdatabase
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  #https://pub.dartlang.org/packages/outline_material_icons
  outline_material_icons: ^0.1.1

  sqflite: ^1.3.0

  path_provider: ^1.6.5

  fluttertoast: ^4.0.0

  #https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.13.4+2

  #https://pub.dev/packages/dio
  dio: ^3.0.9

  #https://pub.dev/packages/json_annotation
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.3.0

  build_runner: ^1.8.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/ic_launcher_foreground.png

  fonts:
    - family: GoogleSansBold
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf

    - family: GoogleSansMedium
      fonts:
        - asset: assets/fonts/GoogleSans-Medium.ttf

    - family: GoogleSansRegular
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
